UniversityManagementSystemApp/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UniversityManagementSystemApp.Models
{
    public class Department
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please Enter Department Code")]
        [StringLength(7, MinimumLength = 2, ErrorMessage = "Length must be 2 to 7 characters")]

        public String Code { get; set; }

        [Required(ErrorMessage = "Please Enter Department Name")]
        public String Name { get; set; }

        public List<Teacher> Teachers { get; set; }
        public List<Course> Courses { get; set; }
    }
}

UniversityManagementSystemApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemApp.Manager;
using UniversityManagementSystemApp.Models;

namespace UniversityManagementSystemApp.Controllers
{
    public class CourseController : Controller
    {
        //
        // GET: /Course/
        public ActionResult Index()
        {
            return View();
        }
        DepartmentManager anDepartmentManager = new DepartmentManager();
        CourseManager anCourseManager = new CourseManager();
      

        public ActionResult SaveCourse()
        {
            //ViewBag.departments = anDepartmentManager.GetAllDepartment();
            ViewBag.departments = GetDepartmentDropDownList();
            ViewBag.semesters = GetSemesterDropDownList();

            // ViewBag.semesters = anCourseManager.GetAllSemester();
            return View();
        }
        [HttpPost]
        public ActionResult SaveCourse(Course course)
        {

            //ViewBag.departments = anDepartmentManager.GetAllDepartment();
            ViewBag.departments = GetDepartmentDropDownList();
            //ViewBag.semesters = anCourseManager.GetAllSemester();
            ViewBag.semesters = GetSemesterDropDownList();
            ViewBag.msg = anCourseManager.Save(course);
            return View();
        }
        private List<SelectListItem> GetDepartmentDropDownList()
        {
            var departments = anDepartmentManager.GetAllDepartment();
            List<SelectListItem> items = new List<SelectListItem>()
            {
                new SelectListItem(){Value="", Text="---Select---"}
            };
            foreach (Department dept in departments)
            {
                SelectListItem item = new SelectListItem() { Value = dept.Id.ToString(), Text = dept.Name };
                items.Add(item);
            }
            return items;
        }

        private List<SelectListItem> GetSemesterDropDownList()
        {
            var semesters = anCourseManager.GetAllSemester();
            List<SelectListItem> items = new List<SelectListItem>()
            {
                new SelectListItem(){Value="", Text="---Select---"}
            };
            foreach (Semester semester in semesters)
            {
                SelectListItem item = new SelectListItem() { Value = semester.Id.ToString(), Text = semester.Name };
                items.Add(item);
            }
            return items;
        }
	}
}

UniversityManagementSystemApp/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemApp.Manager;
using UniversityManagementSystemApp.Models;

namespace UniversityManagementSystemApp.Controllers
{
    public class DepartmentController : Controller
    {
        DepartmentManager aDepartmentManager = new DepartmentManager();
       
        TeacherManager aTeacherManager = new TeacherManager();
        CourseManager aCourseManager = new CourseManager();
        //
        //
        // GET: /Department/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SaveDepartment()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SaveDepartment(Department department)
        {
            ViewBag.msg = aDepartmentManager.SaveDepartment(department);
            return View();
        }

        public ActionResult ViewDepartment()
        {
            ViewBag.departments = aDepartmentManager.GetAllDepartment();
            return View();
        }
        //pari na vai
        public ActionResult CourseAssaignTeacher()
        {
            ViewBag.departments = aDepartmentManager.GetAllDepartment();
            return View();
        }
        [HttpPost]
        public ActionResult CourseAssaignTeacher(Teacher teacher)
        {
            ViewBag.departments = aDepartmentManager.GetAllDepartment();
            ViewBag.assaigned = aTeacherManager.AssaignCourseTeacher(teacher);
            return View();
        }

        public JsonResult GetTeacherCourseByDepartmentId(int id)
        {
            var teacherInfo = aDepartmentManager.GetTeacherByDepartmentId(id);
            var courseInfo = aDepartmentManager.GetCourseByDepartmentId(id);
            Department department = new Department();
            department.Courses = courseInfo;
            department.Teachers = teacherInfo;
            return Json(department);
        }

        public JsonResult GetTeacherInfoById(int id)
        {
            var teacherInfo = aDepartmentManager.GetTeacherInfoById(id);
            return Json(teacherInfo);
        }
        public JsonResult GetCourseInfoById(int id)
        {
            var courseInfo = aDepartmentManager.GetCourseInfoById(id);
            return Json(courseInfo);
        }

        public ActionResult ViewCourseStatics()
        {
            ViewBag.departments = aDepartmentManager.GetAllDepartment();

            return View();
        }
        [HttpPost]
        public ActionResult ViewCourseStatics(int id)
        {
            ViewBag.departments = aDepartmentManager.GetAllDepartment();

            return View();
        }
        public JsonResult GetCoursesByDepartmentId(int id)
        {
            var courses = aCourseManager.GetAllCourses(id);

            foreach (Course course in courses)
            {

                course.TeacherName = aTeacherManager.GetAssaigned(course.Id).ToString();
            }


            return Json(courses);
        }

        public ActionResult UnassignCourses()
        {

            return View();
        }
        [HttpPost]
        public ActionResult UnassignCourses(Course course)
        {
            ViewBag.Assigned =
            ViewBag.Message = aDepartmentManager.UnassignCourses();

            return View();
        }
        public JsonResult IsCourseAssigned(int aVal)
        {


            var returnObj = aDepartmentManager.IsCourseAssigned(aVal);


            return Json(returnObj);
        }

	}
}

UniversityManagementSystemApp/Controllers/EnrollController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemApp.Manager;
using UniversityManagementSystemApp.Models;

namespace UniversityManagementSystemApp.Controllers
{
    public class EnrollController : Controller
    {
        //
        // GET: /Enroll/
       
        EnrollManager anStudentManger = new EnrollManager();
        //
        // GET: /Enroll/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Save()
        {
            ViewBag.students = anStudentManger.GetAllStudentRegNo();
            return View();
        }
        [HttpPost]
        public ActionResult Save(Student student)
        {
            ViewBag.students = anStudentManger.GetAllStudentRegNo();
            ViewBag.msg = anStudentManger.Save(student);
            return View();
        }
        public JsonResult GetStudentInfo(Student student)
        {
            var studentInfo = anStudentManger.GetStudentDetailsWithRegNo(student);
            var courses = anStudentManger.GetAllCourses(studentInfo.DepartmentId);
            studentInfo.Courses = courses;
            return Json(studentInfo);
        }

        public ActionResult SaveResult()
        {
            ViewBag.students = anStudentManger.GetAllStudentRegNo();

            return View();
        }
        [HttpPost]
        public ActionResult SaveResult(Student student)
        {

            ViewBag.students = anStudentManger.GetAllStudentRegNo();
            ViewBag.msg = anStudentManger.SaveResult(student);

            return View();
        }

        public JsonResult GetStudentInformation(Student student)
        {
            var studentInfo = anStudentManger.GetStudentDetailsWithRegNo(student);
            var courses = anStudentManger.GetAllEnrollCourses(student.Id);
            studentInfo.Courses = courses;
            return Json(studentInfo);
        }
	}
}

UniversityManagementSystemApp/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UniversityManagementSystemApp.Controllers
{
    public class IndexController : Controller
    {
        //
        // GET: /Index/
        public ActionResult Index()
        {
            return View();
        }
	}
}

UniversityManagementSystemApp/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemApp.Manager;
using UniversityManagementSystemApp.Models;

namespace UniversityManagementSystemApp.Controllers
{
    public class TeacherController : Controller
    {
        DepartmentManager aDepartmentManager = new DepartmentManager();
        TeacherManager aTeacherManager = new TeacherManager();
        //
        // GET: /Teacher/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SaveTeacher()
        {
            ViewBag.departments = GetDepartmentDropDownList();
            ViewBag.designations = GetDesignationDropDownList();
            return View();
        }
        [HttpPost]
        public ActionResult SaveTeacher(Teacher teacher)
        {
            ViewBag.departments = GetDepartmentDropDownList();
            ViewBag.designations = GetDesignationDropDownList();
            ViewBag.msg = aTeacherManager.SaveTeacher(teacher);
            return View();
        }
        private List<SelectListItem> GetDepartmentDropDownList()
        {
            var departments = aDepartmentManager.GetAllDepartment();
            List<SelectListItem> items = new List<SelectListItem>()
            {
                new SelectListItem(){Value="", Text="---Select---"}
            };
            foreach (Department dept in departments)
            {
                SelectListItem item = new SelectListItem() { Value = dept.Id.ToString(), Text = dept.Name };
                items.Add(item);
            }
            return items;
        }

        private List<SelectListItem> GetDesignationDropDownList()
        {
            var designations = aDepartmentManager.GetAllDesignation();
            List<SelectListItem> items = new List<SelectListItem>()
            {
                new SelectListItem(){Value="", Text="---Select---"}
            };
            foreach (Teacher teacher in designations)
            {
                SelectListItem item = new SelectListItem() { Value = teacher.DesignationId.ToString(), Text = teacher.DesignationName };
                items.Add(item);
            }
            return items;
        }

	}
}

UniversityManagementSystemApp/Views/Department/CourseAssaignTeacher.cshtml
@using UniversityManagementSystemApp.Models
@{
    ViewBag.Title = "Course Assaign Teacher";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <link href="~/Content/Site.css" rel="stylesheet" /> > 
    @*<link href="~/Content/sweetalert2/sweetalert2.min.css" rel="stylesheet" />*@
    <title>CourseAssaignTeacher</title>
    <style>
        body {
            background-color: #a66794;
        }
   label.error {
        color: rgb(5, 7, 12);
        font-style: italic;
    }

    </style >

</head>
<body>
    
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top ">

        <div class="navbar-header">

            <!--for hamburger Icon when NavBar collapses-->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-2" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <div>
                @Html.ActionLink("University Management System", "Index", "index", null, new { @class = "navbar-brand" })
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown ">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Student</span> <span class="caret"></span></a>
                    <ul class="dropdown-menu bg-green-gradient" role="menu">
                        <li> @Html.ActionLink("Regster New Student", "Save", "Student")</li>
                        @*<li> @Html.ActionLink("Student Information ", "ShowStudentInfo", "Student")</li>*@

                    </ul>
                </li>
                <li class="dropdown ">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Teacher</span> <span class="caret"></span></a>
                    <ul class="dropdown-menu bg-green-gradient" role="menu">
                        <li> @Html.ActionLink("Save New Teacher", "SaveTeacher", "Teacher")</li>
                        <li> @Html.ActionLink("Course Assign to Teacher", "CourseAssaignTeacher", "Department")</li>
                    </ul>
                </li>
                <li class="dropdown ">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Department</span> <span class="caret"></span></a>
                    <ul class="dropdown-menu bg-green-gradient" role="menu">
                        <li> @Html.ActionLink("Save New Department", "SaveDepartment", "Department")</li>
                        <li> @Html.ActionLink("Show Department Details", "ViewDepartment", "Department")</li>
                    </ul>
                </li>
                <li class="dropdown ">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Course</span> <span class="caret"></span></a>
                    <ul class="dropdown-menu bg-green-gradient" role="menu">
                        <li> @Html.ActionLink("Save New Course", "SaveCourse", "Course")</li>
                        <li> @Html.ActionLink("Show Course Statics", "ViewCourseStatics", "Department")</li>
                        <li> @Html.ActionLink("Enroll in a course", "Save", "Enroll")</li>
                    </ul>
                </li>
                <li class="dropdown ">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Result</span> <span class="caret"></span></a>
                    <ul class="dropdown-menu bg-green-gradient" role="menu">
                        <li> @Html.ActionLink("Save Student Result", "SaveResult", "Enroll")</li>
                        <li> @Html.ActionLink("Show Result Statics", "ViewStudentResult", "Student")</li>

                    </ul>
                </li>
                <li class="dropdown ">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Class Room</span> <span class="caret"></span></a>
                    <ul class="dropdown-menu bg-green-gradient" role="menu">
                        <li> @Html.ActionLink("Allocate Classrooms", "AllocateClassRoom", "AllocateClassroom")</li>

                        <li> @Html.ActionLink("Show Class Schedule", "ShowClassSchedule", "ClassRoom")</li>
                    </ul>
                </li>
                <li class="dropdown ">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Action</span> <span class="caret"></span></a>
                    <ul class="dropdown-menu bg-green-gradient" role="menu">
                        <li> @Html.ActionLink("UnAssign Course", "UnassignCourses", "Department")</li>
                        <li> @Html.ActionLink("UnAllocate Classrooms", "UnAllocateClassRoom", "ClassRoom")</li>

                    </ul>
                </li>
            </ul>


        </div>
    </nav>
   

    <div>


        <fieldset>
            <legend>Course Assaign To Teacher</legend>
            <form class="form-horizontal main-center" method="POST" id="CourseAssaign">


                <div class="form-group">
                    <label class="control-label col-sm-2" for="DepartmentId">Department</label>
                    <div class="col-sm-6">
                        <select id="DepartmentId" name="DepartmentId" class="form-control" onchange="">
                            <option value="">Select</option>

                            @foreach (Department department in ViewBag.departments)
                            {
                                <option value="@department.Id">@department.Name</option>
                            }


                        </select>
                    </div>

                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2" for="Id">Teacher</label>
                    <div class="col-sm-6">
                        <select id="Id" name="Id" class="form-control" onchange=""></select>
                    </div>
                </div>


                <div class="form-group">
                    <label class="control-label col-sm-2" for="CreditTake">Credit to be taken</label>
                    <div class="col-sm-6">
                        <input readonly id="CreditTake" name="CreditTake" type="text" value="" />

                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2" for="CreditLeft">Remaining Credit</label>
                    <div class="col-sm-6">
                        <input readonly id="CreditLeft" name="CreditLeft" type="text" value="" />

                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2" for="CourseId">Course Code</label>
                    <div class="col-sm-6">
                        <select id="CourseId" name="CourseId" class="form-control" onchange=""></select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2" for="Name">Name</label>
                    <div class="col-sm-6">
                        <input readonly id="Name" name="Name" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2" for="Credit">Credit</label>
                    <div class="col-sm-6">
                        <input readonly id="Credit" name="Credit" type="text" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default" onclick="myFunction()" value="submit">Save</button>
                    </div>
                </div>
            </form>
        </fieldset>
        @if (ViewBag.assaigned != null)
        {
            if (ViewBag.assaigned == 2)
            {
                <label>Course already assaigned !!!</label>

            }
            else
            {
                <label>Course assaigned sucessfully !!!</label>

            }

        }
    </div>
    <footer class="container conmain-footer">
        <div class="pull-right hidden-xs">


            <strong>Copyright &copy; @DateTime.Now.Year <a href="#">2NXY</a>.</strong> All rights reserved.
        </div>
    </footer>
    @section scripts{
        <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Content/sweetalert2/sweetalert2.min.js"></script>
        <script>

            $(document).ready(function () {
                $("#DepartmentId").change(function () {
                    var deptId = $("#DepartmentId").val();
                    $("#CourseId").empty();
                    $("#Id").empty();
                    $("#CourseId").append('<option value="">Select</option>');
                    $("#Id").append('<option value="">Select</option>');
                    var json = { id: deptId };
                    $.ajax({
                        type: "POST",
                        url: '/Department/GetTeacherCourseByDepartmentId',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (data) {
                            $.each(data.Teachers, function (key, value) {
                                $("#Id").append('<option value="' + value.Id + '">' + value.Name + '</option>');
                            });
                            $.each(data.Courses, function (key, value) {
                                $("#CourseId").append('<option value="' + value.Id + '">' + value.Code + '</option>');

                            });

                        }
                    });
                });

                $("#Id").change(function () {
                    var tId = $("#Id").val();
                    $("#CreditTake").empty();
                    $("#CreditLeft").empty();
                    var json = { id: tId };
                    $.ajax({
                        type: "POST",
                        url: '/Department/GetTeacherInfoById',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (data) {

                            $("#CreditTake").val(data.CreditTake);
                            $("#CreditLeft").val(data.CreditLeft);
                        }
                    });
                });

                $("#CourseId").change(function () {
                    var cId = $("#CourseId").val();
                    $("#Name").empty();
                    $("#Credit").empty();
                    var json = { id: cId };
                    $.ajax({
                        type: "POST",
                        url: '/Department/GetCourseInfoById',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (data) {

                            $("#Name").val(data.Name);
                            $("#Credit").val(data.Credit);
                        }
                    });
                });
//vaiya k dekhate hobe.hoi nai eta faltu.
                $("form").submit(function () {
                    var remain = $('#CreditLeft').val();
                    var credit = $('#Credit').val();
                  //  alert(remain +" , " + credit);
                    if ((remain - credit) < 0) {

                        //Swal.fire({
                        //    title: 'Are you sure?',
                        //    text: "You won't be able to revert this!",
                        //    type: 'warning',
                        //    showCancelButton: true,
                        //    confirmButtonColor: '#3085d6',
                        //    cancelButtonColor: '#d33',
                        //    confirmButtonText: 'Yes, delete it!'
                        //}).then((result) => {
                        //    if (result.value) {
                        //        Swal.fire(
                        //            'Deleted!',
                        //            'Your file has been deleted.',
                        //            'success'
                        //        )
                        //    }
                        //});
                        //return Swal.fire('Course credit is more than Remaining Credit . Do you want to proceed?');
                        return confirm('Course credit is more than Remaining Credit . Do you want to proceed?');
                    }
                });


                $("#CourseAssaign").validate({
                    rules: {
                        DepartmentId: "required",
                        CourseId: "required",
                        Id: "required"

                    },
                    messages: {
                        DepartmentId: "Please select department",
                        CourseId: "Please select any Course",
                        Id: "Please select Teacher"
                    }
                });

            });
        </script>
    }
</body>
</html>

UniversityManagementSystemApp/Views/Department/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>