UniversityManagementSystemApp/Models/AllocateClassroom.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UniversityManagementSystemApp.Models
{
    public class AllocateClassroom
    {
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public int CourseId { get; set; }
        public int RoomId { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public string Allocate { get; set; }
        public string Day { get; set; }
    }
}

UniversityManagementSystemApp/Models/ClassRoom.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UniversityManagementSystemApp.Models
{
    public class ClassRoom
    {

        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public string Department { get; set; }
        public int CourseId { get; set; }
        public string CourseCode { get; set; }
        public string Course { get; set; }
        public int RoomId { get; set; }
        public string RoomNo { get; set; }
        public string Day { get; set; }
        public string FromTime { get; set; }
        public string ToTime { get; set; }
        public string Allocate { get; set; }
    }
}

UniversityManagementSystemApp/Controllers/AllocateClassroomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemApp.Manager;
using UniversityManagementSystemApp.Models;

namespace UniversityManagementSystemApp.Controllers
{
    public class AllocateClassroomController : Controller
    {
        AllocateClassroomManager ClassroomManager = new AllocateClassroomManager();
        //
        // GET: /University/
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult AllocateClassroom()
        {
            ViewBag.departments = ClassroomManager.GetAllDepartments();
            ViewBag.rooms = ClassroomManager.GetAllRooms();

            return View();
        }

        [HttpPost]

        public ActionResult AllocateClassroom(AllocateClassroom allocateClassroom)
        {
            ViewBag.departments = ClassroomManager.GetAllDepartments();
            ViewBag.rooms = ClassroomManager.GetAllRooms();
            ViewBag.msg = ClassroomManager.Save(allocateClassroom);
            return View();
        }
        public JsonResult GetCourseByDepartmentId(AllocateClassroom allocateClassroom)
        {
            var courses = ClassroomManager.GetAllCourses(allocateClassroom);
            return Json(courses);
        }
    }
	
}

UniversityManagementSystemApp/Controllers/ClassRoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemApp.Manager;
using UniversityManagementSystemApp.Models;

namespace UniversityManagementSystemApp.Controllers
{
    public class ClassRoomController : Controller
    {
        //
        // GET: /ClassRoom/
        public ActionResult Index()
        {
            return View();
        }
        ClassRoomManager aClassRoomManager = new ClassRoomManager();
        StudentManager aStudentManager = new StudentManager();
        public ActionResult ShowClassSchedule()
        {

            ViewBag.Departments = aStudentManager.GetAllDepartments();
            // ViewBag.Departments = GetDepartmentForDropDownList();

            //ViewBag.ClassSchedule = aClassRoomManager.GetAllAllocatedClassRoomWithout();
            return View();
        }
        [HttpPost]
        public ActionResult ShowClassSchedule(ClassRoom classRoom)
        {
            ViewBag.Departments = aStudentManager.GetAllDepartments();

            //ViewBag.Departments = GetDepartmentForDropDownList();
            /*List<Course> courses = aClassRoomManager.GetAllCourses(classRoom);
            ViewBag.Courses = courses;
            foreach (Course course in courses)
            {
                List<ClassRoom> classRooms = aClassRoomManager.GetAllClassRooms(course);
                ViewBag.ClassRooms = classRooms;
                return View();
            }*/

            return View();
        }
        public JsonResult GetCoursesByDepartmentId(ClassRoom classRoom)
        {
            var courses = aClassRoomManager.GetAllCourses(classRoom);


            List<Course> courseDetails = new List<Course>();
            foreach (Course course in courses)
            {
                List<ClassRoom> classRooms = aClassRoomManager.GetAllClassRooms(course.Id);
                if (classRooms.Count < 1)
                {
                    course.RoomInfo = "Not scheduled yet";

                }
                else
                {
                    foreach (ClassRoom room in classRooms)
                    {
                        course.RoomInfo += "R No: " + room.RoomNo + ", " + room.Day + ", " + room.FromTime + "-" +
                                           room.ToTime + "; </br> ";
                    }
                }
                course.ClassRooms = classRooms;
                course.Code = course.Code;
                course.Name = course.Name;
                courseDetails.Add(course);
            }

            return Json(courseDetails);
        }

        public ActionResult AllocateClassRoom()
        {
            return View();
        }
        public ActionResult UnAllocateClassRoom()
        {

            return View();
        }

        [HttpPost]
        public ActionResult UnAllocateClassRoom(ClassRoom classRoom)
        {
            ViewBag.Message = aClassRoomManager.UnAllocateClassRoom();
            return View();
        }
	}
}

UniversityManagementSystemApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemApp.Manager;
using UniversityManagementSystemApp.Models;

namespace UniversityManagementSystemApp.Controllers
{
    public class CourseController : Controller
    {
        //
        // GET: /Course/
        public ActionResult Index()
        {
            return View();
        }
        DepartmentManager anDepartmentManager = new DepartmentManager();
        CourseManager anCourseManager = new CourseManager();
      

        public ActionResult SaveCourse()
        {
            //ViewBag.departments = anDepartmentManager.GetAllDepartment();
            ViewBag.departments = GetDepartmentDropDownList();
            ViewBag.semesters = GetSemesterDropDownList();

            // ViewBag.semesters = anCourseManager.GetAllSemester();
            return View();
        }
        [HttpPost]
        public ActionResult SaveCourse(Course course)
        {

            //ViewBag.departments = anDepartmentManager.GetAllDepartment();
            ViewBag.departments = GetDepartmentDropDownList();
            //ViewBag.semesters = anCourseManager.GetAllSemester();
            ViewBag.semesters = GetSemesterDropDownList();
            ViewBag.msg = anCourseManager.Save(course);
            return View();
        }
        private List<SelectListItem> GetDepartmentDropDownList()
        {
            var departments = anDepartmentManager.GetAllDepartment();
            List<SelectListItem> items = new List<SelectListItem>()
            {
                new SelectListItem(){Value="", Text="---Select---"}
            };
            foreach (Department dept in departments)
            {
                SelectListItem item = new SelectListItem() { Value = dept.Id.ToString(), Text = dept.Name };
                items.Add(item);
            }
            return items;
        }

        private List<SelectListItem> GetSemesterDropDownList()
        {
            var semesters = anCourseManager.GetAllSemester();
            List<SelectListItem> items = new List<SelectListItem>()
            {
                new SelectListItem(){Value="", Text="---Select---"}
            };
            foreach (Semester semester in semesters)
            {
                SelectListItem item = new SelectListItem() { Value = semester.Id.ToString(), Text = semester.Name };
                items.Add(item);
            }
            return items;
        }
	}
}

UniversityManagementSystemApp/Controllers/EnrollController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemApp.Manager;
using UniversityManagementSystemApp.Models;

namespace UniversityManagementSystemApp.Controllers
{
    public class EnrollController : Controller
    {
        //
        // GET: /Enroll/
       
        EnrollManager anStudentManger = new EnrollManager();
        //
        // GET: /Enroll/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Save()
        {
            ViewBag.students = anStudentManger.GetAllStudentRegNo();
            return View();
        }
        [HttpPost]
        public ActionResult Save(Student student)
        {
            ViewBag.students = anStudentManger.GetAllStudentRegNo();
            ViewBag.msg = anStudentManger.Save(student);
            return View();
        }
        public JsonResult GetStudentInfo(Student student)
        {
            var studentInfo = anStudentManger.GetStudentDetailsWithRegNo(student);
            var courses = anStudentManger.GetAllCourses(studentInfo.DepartmentId);
            studentInfo.Courses = courses;
            return Json(studentInfo);
        }

        public ActionResult SaveResult()
        {
            ViewBag.students = anStudentManger.GetAllStudentRegNo();

            return View();
        }
        [HttpPost]
        public ActionResult SaveResult(Student student)
        {

            ViewBag.students = anStudentManger.GetAllStudentRegNo();
            ViewBag.msg = anStudentManger.SaveResult(student);

            return View();
        }

        public JsonResult GetStudentInformation(Student student)
        {
            var studentInfo = anStudentManger.GetStudentDetailsWithRegNo(student);
            var courses = anStudentManger.GetAllEnrollCourses(student.Id);
            studentInfo.Courses = courses;
            return Json(studentInfo);
        }
	}
}

UniversityManagementSystemApp/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UniversityManagementSystemApp.Controllers
{
    public class IndexController : Controller
    {
        //
        // GET: /Index/
        public ActionResult Index()
        {
            return View();
        }
	}
}

UniversityManagementSystemApp/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagementSystemApp.Manager;
using UniversityManagementSystemApp.Models;

namespace UniversityManagementSystemApp.Controllers
{
    public class TeacherController : Controller
    {
        DepartmentManager aDepartmentManager = new DepartmentManager();
        TeacherManager aTeacherManager = new TeacherManager();
        //
        // GET: /Teacher/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SaveTeacher()
        {
            ViewBag.departments = GetDepartmentDropDownList();
            ViewBag.designations = GetDesignationDropDownList();
            return View();
        }
        [HttpPost]
        public ActionResult SaveTeacher(Teacher teacher)
        {
            ViewBag.departments = GetDepartmentDropDownList();
            ViewBag.designations = GetDesignationDropDownList();
            ViewBag.msg = aTeacherManager.SaveTeacher(teacher);
            return View();
        }
        private List<SelectListItem> GetDepartmentDropDownList()
        {
            var departments = aDepartmentManager.GetAllDepartment();
            List<SelectListItem> items = new List<SelectListItem>()
            {
                new SelectListItem(){Value="", Text="---Select---"}
            };
            foreach (Department dept in departments)
            {
                SelectListItem item = new SelectListItem() { Value = dept.Id.ToString(), Text = dept.Name };
                items.Add(item);
            }
            return items;
        }

        private List<SelectListItem> GetDesignationDropDownList()
        {
            var designations = aDepartmentManager.GetAllDesignation();
            List<SelectListItem> items = new List<SelectListItem>()
            {
                new SelectListItem(){Value="", Text="---Select---"}
            };
            foreach (Teacher teacher in designations)
            {
                SelectListItem item = new SelectListItem() { Value = teacher.DesignationId.ToString(), Text = teacher.DesignationName };
                items.Add(item);
            }
            return items;
        }

	}
}

UniversityManagementSystemApp/Views/ClassRoom/AllocateClassRoom.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AllocateClassRoom</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

UniversityManagementSystemApp/Views/ClassRoom/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

UniversityManagementSystemApp/Views/ClassRoom/ShowClassSchedule.cshtml
@{
    ViewBag.Title = "ShowClassSchedule";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Class Schedule</title>
    <style>
      

        body {
            background-color: #c0d0d9;
        }
    </style>
</head>
<body>
<div>
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top ">

        <div class="navbar-header">

            <!--for hamburger Icon when NavBar collapses-->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-2" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <div>
                @Html.ActionLink("University Management System", "Index", "index", null, new { @class = "navbar-brand" })
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown ">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Student</span> <span class="caret"></span></a>
                    <ul class="dropdown-menu bg-green-gradient" role="menu">
                        <li> @Html.ActionLink("Regster New Student", "Save", "Student")</li>
                        @*<li> @Html.ActionLink("Student Information ", "ShowStudentInfo", "Student")</li>*@

                    </ul>
                </li>
                <li class="dropdown ">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Teacher</span> <span class="caret"></span></a>
                    <ul class="dropdown-menu bg-green-gradient" role="menu">
                        <li> @Html.ActionLink("Save New Teacher", "SaveTeacher", "Teacher")</li>
                        <li> @Html.ActionLink("Course Assign to Teacher", "CourseAssaignTeacher", "Department")</li>
                    </ul>
                </li>
                <li class="dropdown ">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Department</span> <span class="caret"></span></a>
                    <ul class="dropdown-menu bg-green-gradient" role="menu">
                        <li> @Html.ActionLink("Save New Department", "SaveDepartment", "Department")</li>
                        <li> @Html.ActionLink("Show Department Details", "ViewDepartment", "Department")</li>
                    </ul>
                </li>
                <li class="dropdown ">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Course</span> <span class="caret"></span></a>
                    <ul class="dropdown-menu bg-green-gradient" role="menu">
                        <li> @Html.ActionLink("Save New Course", "SaveCourse", "Course")</li>
                        <li> @Html.ActionLink("Show Course Statics", "ViewCourseStatics", "Department")</li>
                        <li> @Html.ActionLink("Enroll in a course", "Save", "Enroll")</li>
                    </ul>
                </li>
                <li class="dropdown ">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Result</span> <span class="caret"></span></a>
                    <ul class="dropdown-menu bg-green-gradient" role="menu">
                        <li> @Html.ActionLink("Save Student Result", "SaveResult", "Enroll")</li>
                        <li> @Html.ActionLink("Show Result Statics", "ViewStudentResult", "Student")</li>

                    </ul>
                </li>
                <li class="dropdown ">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Class Room</span> <span class="caret"></span></a>
                    <ul class="dropdown-menu bg-green-gradient" role="menu">
                        <li> @Html.ActionLink("Allocate Classrooms", "AllocateClassRoom", "AllocateClassroom")</li>

                        <li> @Html.ActionLink("Show Class Schedule", "ShowClassSchedule", "ClassRoom")</li>
                    </ul>
                </li>
                <li class="dropdown ">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Action</span> <span class="caret"></span></a>
                    <ul class="dropdown-menu bg-green-gradient" role="menu">
                        <li> @Html.ActionLink("UnAssign Course", "UnassignCourses", "Department")</li>
                        <li> @Html.ActionLink("UnAllocate Classrooms", "UnAllocateClassRoom", "ClassRoom")</li>

                    </ul>
                </li>
            </ul>


        </div>
    </nav>
</div>

    <div>
        <h3> Class Schedule</h3>
        @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal", id = "viewStudentResult" }))
        {

            <div class="form-group">

                <label class="col-md-4 control-label" for="departmentId">Select Department</label>
                <div class="col-md-4">
                    <select class="form-control" name="departmentId" id="departmentId">
                        <option value="">--Select--</option>
                        @foreach (var department in ViewBag.Departments)
                        {
                            <option value="@department.Id">@department.Code</option>
                        }
                    </select>



                </div>

            </div>
        }

    </div>

    <table id="myTable" class="table table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th>Course Code</th>
                <th>Name</th>
                <th>Schedule Info</th>
            </tr>
        </thead>
        <tbody id="tableBody"></tbody>
    </table>
    <footer class="container conmain-footer">
        <div class="pull-right hidden-xs">


            <strong>Copyright &copy; @DateTime.Now.Year <a href="#">2NXY</a>.</strong> All rights reserved.
        </div>
    </footer>
    @section scripts
    {
        <script>
            $(document).ready(function () {
                $("#myTable").hide();
                $("#departmentId").change(function () {
                    var deptId = $("#departmentId").val();
                    $("#myTable").show();
                    $("#tableBody").empty();
                    var json = { departmentId: deptId };
                    $.ajax({
                        type: "POST",
                        url: '/ClassRoom/GetCoursesByDepartmentId',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (data) {

                            $.each(data, function (key, value) {


                                $("#tableBody").append('<tr><td>' + value.Code + '</td><td>' + value.Name + '</td><td>' + value.RoomInfo + '</td></tr>');

                            });
                        }
                    });
                });
            });
        </script>
    }



</body>
</html>

UniversityManagementSystemApp/Views/ClassRoom/UnAllocateClassRoom.cshtml
@{
    ViewBag.Title = "UnAllocateClassRoom";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UnassignCourses</title>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <style>
        body {
            background-color: #769cb0;
        }
    </style>
</head>
<body>

    


    <div>
        <nav class="navbar navbar-default navbar-custom navbar-fixed-top ">

            <div class="navbar-header">

                <!--for hamburger Icon when NavBar collapses-->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-2" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
                <div>
                    @Html.ActionLink("University Management System", "Index", "index", null, new { @class = "navbar-brand" })
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown ">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Student</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu bg-green-gradient" role="menu">
                            <li> @Html.ActionLink("Regster New Student", "Save", "Student")</li>
                            @*<li> @Html.ActionLink("Student Information ", "ShowStudentInfo", "Student")</li>*@

                        </ul>
                    </li>
                    <li class="dropdown ">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Teacher</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu bg-green-gradient" role="menu">
                            <li> @Html.ActionLink("Save New Teacher", "SaveTeacher", "Teacher")</li>
                            <li> @Html.ActionLink("Course Assign to Teacher", "CourseAssaignTeacher", "Department")</li>
                        </ul>
                    </li>
                    <li class="dropdown ">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Department</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu bg-green-gradient" role="menu">
                            <li> @Html.ActionLink("Save New Department", "SaveDepartment", "Department")</li>
                            <li> @Html.ActionLink("Show Department Details", "ViewDepartment", "Department")</li>
                        </ul>
                    </li>
                    <li class="dropdown ">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Course</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu bg-green-gradient" role="menu">
                            <li> @Html.ActionLink("Save New Course", "SaveCourse", "Course")</li>
                            <li> @Html.ActionLink("Show Course Statics", "ViewCourseStatics", "Department")</li>
                            <li> @Html.ActionLink("Enroll in a course", "Save", "Enroll")</li>
                        </ul>
                    </li>
                    <li class="dropdown ">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Result</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu bg-green-gradient" role="menu">
                            <li> @Html.ActionLink("Save Student Result", "SaveResult", "Enroll")</li>
                            <li> @Html.ActionLink("Show Result Statics", "ViewStudentResult", "Student")</li>

                        </ul>
                    </li>
                    <li class="dropdown ">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Class Room</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu bg-green-gradient" role="menu">
                            <li> @Html.ActionLink("Allocate Classrooms", "AllocateClassRoom", "AllocateClassroom")</li>

                            <li> @Html.ActionLink("Show Class Schedule", "ShowClassSchedule", "ClassRoom")</li>
                        </ul>
                    </li>
                    <li class="dropdown ">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span> Action</span> <span class="caret"></span></a>
                        <ul class="dropdown-menu bg-green-gradient" role="menu">
                            <li> @Html.ActionLink("UnAssign Course", "UnassignCourses", "Department")</li>
                            <li> @Html.ActionLink("UnAllocate Classrooms", "UnAllocateClassRoom", "ClassRoom")</li>

                        </ul>
                    </li>
                </ul>


            </div>
        </nav>
    </div>
    <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  @using (Html.BeginForm(null, null, FormMethod.Post, new {@class = "form-horizontal", id = "UnAllocateClassRoom"}))
            {
                <div class="form-group">
                    <label class="col-md-4 control-label" for="unAllocateClassRoom"></label>
                    <div class="col-md-4">
                        <button id="unAllocateClassRoom" onclick="return confirm('You are unallocationg all classrooms ,Are you sure?');" name="unAllocateClassRoom" class="btn btn-primary">Unallocate ClassRoom</button>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control-label"></label>
                    <div class="col-md-4 ">
                        @if (ViewBag.Message != null)
                        {
                            <label class="label-success">@ViewBag.Message</label>
                        }
                    </div>
                </div>
            }
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

    <footer class="container conmain-footer">
        <div class="pull-right hidden-xs">


            <strong>Copyright &copy; @DateTime.Now.Year <a href="#">2NXY</a>.</strong> All rights reserved.
        </div>
    </footer>
            <script src="~/Scripts/bootstrap.min.js"></script>

            <script src="~/Scripts/jquery-1.10.2.js"></script>
</body>

</html>